# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 807918c1d581f6a65a1eadd6be098a08b080d8c0b1bf4c1f66769b0f36d1d4681ed3a36117d4f43c3a238fac31eacb20180a87538a550da549aeb1d945c03446

test:
  secret_key_base: d96eba0b98ac5f7dc901927520c4a07a370a16c96bf161df876f8d5221b7b80dea93af47a90b05eb193e993fd3ff14e42800026a62678c77148b0e905fd73973

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
